version: '3.9'

services:
  core:
    image: node:20-alpine3.19
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./backup:/app/backup
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.13
    command: [ --replSet, rs0, --bind_ip_all, --port, "27017" ]
    restart: unless-stopped
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s

  mongo-gui:
    container_name: mongo-gui
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
